image: maven:3.3.9

pipelines:
  custom:
    deploy:
      - step:
          caches:
            - maven
          script: # Modify the commands below to build your repository.
            - (echo $RELEASE_GPG_ENC | base64 --decode > ~/private-key.gpg.enc)
            - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in ~/private-key.gpg.enc -out private-key.gpg -d
            - gpg --import private-key.gpg
            - mvn -V -B -s settings.xml deploy -DaltDeploymentRepository=ossrh::default::https://oss.sonatype.org/service/local/staging/deploy/maven2