name: build
on:
  push:
  pull_request:

jobs:
  compile:
    name: "compile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: ./mvnw compile

  test:
    name: "tests (Alfresco version ${{ matrix.alfresco-version }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - alfresco-version: 6.1.2-ga
            experimental: false
          - alfresco-version: 6.2.0-ga
            experimental: false
          - alfresco-version: 7.1.0.1
            experimental: false
          - alfresco-version: 7.2.0
            experimental: false
          - alfresco-version: 7.3.0
            experimental: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: ./mvnw test -Pcommunity-${{ matrix.alfresco-version }}
