name: build
on:
  push:
  pull_request:

jobs:
  compile:
    name: "compile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Build with Maven
        run: ./mvnw compile

  test:
    name: "tests (Alfresco version ${{ matrix.alfresco-version }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - alfresco-version: 23.1.0
            experimental: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run tests
        run: ./mvnw test -Pcommunity-${{ matrix.alfresco-version }}
